### ISSUE TITLE
uninitialized constant Sass::Script (NameError)

### ISSUE THREAD

**Issue by jtrost** [josh/sprockets-es6#15]
I created a new Rails application, and I added these lines to the Gemfile.
```
gem 'sprockets', '~>3.0.0.beta'
gem 'sprockets-es6'
```
Starting the Rails server returned this error:
```
~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-rails-5.0.1/lib/sass/rails/helpers.rb:11:in `<top (required)>': uninitialized constant Sass::Script (NameError)
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-rails-5.0.1/lib/sass/rails.rb:8:in `require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-rails-5.0.1/lib/sass/rails.rb:8:in `<top (required)>'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-rails-5.0.1/lib/sass-rails.rb:1:in `require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sass-rails-5.0.1/lib/sass-rails.rb:1:in `<top (required)>'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `each'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `block in require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `each'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
  from ~/dev/es6/config/application.rb:7:in `<top (required)>'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.1.rc1/lib/rails/commands/commands_tasks.rb:78:in `require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.1.rc1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.1.rc1/lib/rails/commands/commands_tasks.rb:75:in `tap'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.1.rc1/lib/rails/commands/commands_tasks.rb:75:in `server'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.1.rc1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.1.rc1/lib/rails/commands.rb:17:in `<top (required)>'
  from ~/dev/es6/bin/rails:8:in `require'
  from ~/dev/es6/bin/rails:8:in `<top (required)>'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client/rails.rb:27:in `load'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client/rails.rb:27:in `call'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client/command.rb:7:in `call'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client.rb:26:in `run'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/bin/spring:48:in `<top (required)>'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/binstub.rb:11:in `load'
  from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/binstub.rb:11:in `<top (required)>'
  from ~/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ~/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ~/dev/es6/bin/spring:13:in `<top (required)>'
  from bin/rails:3:in `load'
  from bin/rails:3:in `<main>'
```
Removing ```gem 'sass-rails', '~> 5.0'``` from the Gemfile lets me start the Rails server, but I would still like to use sass-rails with sprockets-es6.

**Comment by lucasmazza** [comment]
Fixed by https://github.com/rails/sass-rails/pull/319, please use `sass-rails` 5.0.2+.
